### PR TITLE
Future expiration and versiosn

### PR DESCRIPTION
**Pull request by ricardocousolr**
Test changes

### CODE REVIEW

**Comment by ricardocousolr** [comment]
ci:test:staging

**Comment by ricardocousolr** [comment]
ci:test:export-import

**Comment by JoyceWang08211** [comment]
Reviewed. Test failures are unrelated. 

1. The following tests failed due to bugs exist in upstream:
LocalFile.CPSitetemplates#SiteTemplateXSS --- LPS-124163
LocalFile.StagingUsecase#TrashEntryReferencePublishing --- LPS-123072
LocalFile.Staging#ViewSimplePublicationAfterDeleteDocumentInGlobal --- LPS-123072
LocalFile.ExportImport#ImportSiteWithMissingReferenceOfPreloadedEntry ---  LPS-123905
LocalFile.Staging#PublishWebContentWithUnchangedReferencedContent ---LPS-123072
LocalFile.ExportImport#ExportImportSiteWithNestedUploadField --- LPS-124004
LocalFile.ExportImport#ExportImportWebcontentWithRepeatField --- LPS-124012
LocalFile.ExportImport#ImportStagedSiteWithCircularReference --- LPS-123091

The above failing tests has been quarantined under [LRQA-63463](https://issues.liferay.com/browse/LRQA-63463).

2. Staging#ViewParentPageNameAfterPublishChangesInChildPage only occurs on jenkins, will be fixed under LRQA-63361.
    StagingUsecase#EditPublishTemplate will be fixed under LRQA-63447.

The above failing tests has been quarantined under [LRQA-63463](https://issues.liferay.com/browse/LRQA-63463).

3. Staging#StagingRemoteDMDocumentType is no longer reproducible.

4. LocalFile.Staging#StagingMultipleDM is fixed under LRQA-63457.
    LocalFile.ExportImport#ExportImportSiteWithReferencedWebContent is fixed under LRQA-63465.

You may need to rebased the current PR when the [fix](https://github.com/brianchandotcom/liferay-portal/pull/96401) is merged into upstream. Or you can cherry pick my [fix](https://github.com/brianchandotcom/liferay-portal/pull/96401) to start a new run. @ricardocousolr 

cc @gaborlovasdotcom

**Comment by ricardocousolr** [comment]
Thanks a lot for your work and your comment @JoyceWang08211! It's really helpful!

**Comment by gaborlovasdotcom** [comment]
@ricardocousolr are we still need this item or it's outdated?

**Comment by ricardocousolr** [comment]
Hi @gaborlovasdotcom,

This was a test PR for https://issues.liferay.com/browse/LPS-128389, but it has been fixed. I'll close it with this comment.

**Pull request closed without merging**
