### PR TITLE
LPS-98322 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LPS-98322

### CODE REVIEW

**Comment by kyle-miho** [comment]
hey @ricardocousolr I sent a pull with a more "faithful" usecase, and it has trouble reproducing the bug, because for some reason, the fragmentEntryLinks are not updating the "wrong" fragmentEntry, this seems to be difficult to reproduce, maybe the parameter map is not setup the same as the way that it is normally performed in the UI way. 

The other test I created originally still works for me after reverting / unreverting, so perhaps you can look at that one again.

**Comment by ricardocousolr** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ricardocousolr** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ricardocousolr** [comment]
Pull request submitted to https://github.com/kyle-miho/liferay-portal/pull/227. [See changes here.](https://github.com/ricardocousolr/liferay-portal/compare/3099a0f~4...3099a0f) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
