### PR TITLE
LPS-140513 Fix infinite SAML redirect

### PR DESCRIPTION
**Pull request by stian-sigvartsen**
Hi Ricardo. In looking for a way to make your solution more generic I came up with this one. Can you review if it meets the requirements and any other thoughts you have got? Thanks!

### CODE REVIEW

**Comment by stian-sigvartsen** [comment]
ci:test:relevant

**Comment by stian-sigvartsen** [comment]
ci:test:saml

**Comment by ricardocousolr** [comment]
Thanks @stian-sigvartsen!

I'll review it, test it and get back to you.

**Comment by ricardocousolr** [comment]
Hi @stian-sigvartsen,

I've tested the solution and it works as expected. I just have a couple of questions to make sure I've understood it correctly:

1. We don't distinguish between the different types of errors we can get from `AssertionConsumerServiceAction`. I assume this is fine but I wanted to make we don't need to treat some of those differently.
2. We don't unset the attribute `WebKeys.BLOCK_LOGIN_PROMPT` at any point. I assume this is fine too because it's not like `SamlWebKeys.SAML_SSO_ERROR` that is set in the `httpSession` but goes in the request.

Also, the failed tests that are unique to this pr don't seem to be related and might be spurious. 

Thanks again for your help!

**Comment by stian-sigvartsen** [comment]
Hi @ricardocousolr . Glad it works as expected for you also!
1. The PR should not change this logic but the idea is `SAML_SSO_ERROR` will contain a language key representing a specific error that means something to the end user. For example the strangers are not allowed message. Are you seeing a generic message instead?
2. It is a good point. The way I set it is via the servlet filter, which means if we add value reverting code it would need to be done after the doFilter() method is invoked. By which point I suspect the `HttpServletResponse` is committed already. Meaning there would be little value in reverting it to `false`, because no servlet filter code would be able to redirect anyway. Do you see a different option for handling it?

**Comment by ricardocousolr** [comment]
Hi @stian-sigvartsen,

1. I see the appropriate message. I was just wondering whether specific types of errors should be handled differently in the logic beyond being handled uniformly by `saml_error.jsp`. It's good then.
2. I've only found [this example of removing an attribute](https://github.com/liferay/liferay-portal/blob/master/portal-kernel/src/com/liferay/portal/kernel/servlet/filters/invoker/InvokerFilter.java#L95-L109) from the `httpServletRequest`, but it might be a special case? If you think the value needs no removing we can go ahead with the pr as is.

**Comment by stian-sigvartsen** [comment]
Thanks @ricardocousolr . Good thoughts to keep in mind for future changes!

**Comment by stian-sigvartsen** [comment]
ci:forward:force

**Comment by ricardocousolr** [comment]
Thank you for all your help, @stian-sigvartsen!

**Comment by stian-sigvartsen** [comment]
ci:forward:force

**Comment by stian-sigvartsen** [comment]
ci:stop

**Pull request closed without merging**
