### PR TITLE
LPS-140513 v3

### PR DESCRIPTION
**Pull request by ricardocousolr**
auto tests

### CODE REVIEW

**Comment by ricardocousolr** [comment]
ci:test:relevant

**Comment by ricardocousolr** [comment]
ci:test:saml

**Comment by ricardocousolr** [comment]
ci:reevaluate:1397401_3325

**Comment by stian-sigvartsen** [comment]
Hi @ricardocousolr . The separation of concerns between the portal core and the SAML modules is not very well defined in this change unfortunately. If we need to change core for this then we should try make it more generalized I think. The great thing is you have identified the existing code that triggers the desirable behaviour so it is likely only the conditions that need a little work.

**Comment by ricardocousolr** [comment]
Hi @stian-sigvartsen, 

You're right. Do you have general suggestions on how to make it better? Should I avoid passing information in the session? Do you know of other places in the portal where we might do something similar?

**Comment by stian-sigvartsen** [comment]
Please see ricardocousolr/liferay-portal/pull/73

**Comment by stian-sigvartsen** [comment]
It is best to avoid passing information in the session unless absolutely necessary. The solution I sent to ricardocousolr/liferay-portal/pull/73 re-uses the SAML_SSO_ERROR session attribute to block login prompt behaviour. This at least does not increase the session usage.

**Pull request closed without merging**
